title: '<p align="center"> Ninda Nurseha Amalina </p>'

logo: /Prof_pic_2.png

description: |
  <p align="center">
    <a href="https://www.linkedin.com/in/nindanrsh/" target="_blank">
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/linkedin/linkedin-original.svg" alt="LinkedIn" width="30" height="30">
    </a>
    &nbsp;&nbsp;
    <a href="https://github.com/amalinand" target="_blank">
      <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" alt="GitHub" width="30" height="30">
    </a>
    &nbsp;&nbsp;
    <a href="https://scholar.google.com/citations?user=vxWv3voAAAAJ&hl=en" target="_blank">
      <img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/googlescholar.svg" alt="Google Scholar" width="30" height="30">
    </a>
  </p>

  <p align="center">
    M.Eng. in Industrial Engineering at Kumoh National Institute of Technology, South Korea | Research Interest in AI-driven decision-making under uncertainty in healthcare systems
    <br><br>
  </p>

github:
  is_project_page: false
  is_user_page: false

theme: jekyll-theme-minimal
#google_analytics: UA-145578661-1
